#alias ec='/opt/emacs/bin/emacsclient -c -nw'
#alias ed='/opt/emacs/bin/emacs --daemon --chdir $HOME'
#alias pc='proxychains'
#alias bind26='numactl --localalloc --physcpubind=6-31'
#alias bind1='numactl --localalloc --physcpubind=31'
#alias cloc='cloc --processes=$(nproc)'
#alias goto-llvm='cd /build/llvm-dev/llvm-project'
#alias goto-rust='cd /build/rust-dev/rust'
#alias socks='https_proxy="socks5://localhost:1080"'
#alias gp='https_proxy="socks5://localhost:1080" git pull --recurse-submodules'
